config/routes.rb
Rails.application.routes.draw do

  get 'bank_accounts/unallocated'
  get 'purchases/paid'
  get 'purchases/draft_index'
  get 'purchases/unpaid'
  get 'purchases/partially_paid'
  get 'report/income_statement'
  get 'report/balance_sheet'
  get 'report/trial_balance'
  get 'report/general_ledger'
  get 'payment_entries/invoice_entry'
  get 'receipt_entries/invoice_entry'
   get 'sales/paid'
  get 'sales/draft_index'
  get 'sales/unpaid'
  get 'sales/partially_paid'
  resources :journals
  resources :journal_entries
  resources :products
    get 'purchases/draft'
   get 'purchases/invoice'
  resources :purchase_entries
  resources :purchases
  resources :contacts
  get 'sales/quote'
  get 'sales/draft'
   get 'sales/invoice'
  resources :sales_entries
  resources :sales
  resources :receipt_entries
  resources :payment_entries
  resources :bank_accounts
  resources :gl_accounts
  resources :transactions
  get 'index/home'
 
  root 'index#home'
  
    resources :transactions do 
    collection { post :import }
  end
  resources :bank_accounts do 
    collection { post :import }
  end
  
   resources :transactions do
    collection do
      delete 'destroy_multiple'
    end
  end
 
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
 
   has_many :transactions
   has_many :payment_entries
   has_many :sales_entries
   
   accepts_nested_attributes_for :transactions
   
 
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
    @transactions = Transaction.all
  end
  

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
    @total = Transaction.all
    @transactions = Transaction.paginate(:per_page => 35, :page => params[:page]).search(params[:search]).searchref(params[:searchref]).order('created_at DESC')
  end
  
  
    def unallocated
    @bank_accounts = BankAccount.all
    @transactions = Transaction.all
  end
  
  
    def import
     Transaction.import(params[:file])
     redirect_to :back, notice: "Transactions imported."
  end
  
 
  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

def destroy_multiple

  Transaction.destroy(params[:transactions])

  respond_to do |format|
    format.html { redirect_to blog_posts_path }
    format.json { head :no_content }
  end

end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to redirect_to :back, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url, notice: 'Bank account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:code, :name, :opening_balance)
    end
    
      private

end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for(@bank_account) do |f| %>
  <% if @bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h2>

      <ul>
      <% @bank_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :opening_balance %><br>
    <%= f.text_field :opening_balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<h1>Editing Bank Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank_account %> |
<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/index.html.erb
<br>
<%= link_to 'New Bank account', new_bank_account_path, class: "btn btn-primary col-md-3" %>


<br><br>
<div class="card">
 <div class="card-body table-responsive">
   <table class="table table-hover">
    <thead class="text-warning">
      <tr>
        <th colspan="1"></th>
        <th scope="col">Account code</th>
        <th scope="col">Account name</th>
        <th scope="col">Account ID</th>
        <th scope="col">Account Balance</th>
        <th colspan="1"></th>
      </tr>
      </thead>

  <tbody>
    <% @bank_accounts.each do |bank_account| %>
      <tr>
        <td></td>
        <td><%=link_to bank_account.code, bank_account %></td>
         <td><%= link_to bank_account.name, bank_account  %></td>
         <td><%= link_to bank_account.id, bank_account  %></td>
          <td><%= number_to_currency(bank_account.transactions.sum(:amount), :unit => "R ")  %></td>
          <td><%= link_to 'Edit', edit_bank_account_path(bank_account) %> |
              <%= link_to 'Destroy', bank_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>


     <td></td>
     <td><%= link_to "Unallocated transactions", bank_accounts_unallocated_path %></td>
     <td></td>
     <td></td>
      <td><% @total = 0 %><% @transactions.each do |transaction| %>
      <% if transaction.gl_account_id == nil%>
          <% @total += transaction.amount.to_f.round(2) %>
          <% end %>
          <% end %>
          <%= link_to  number_to_currency(@total, :unit => "R "),bank_accounts_unallocated_path    %></td>
          <td></td>
     </thead>
  </tbody>
</table>

<br>

app/views/bank_accounts/new.html.erb
<h1>New Bank Account</h1>

<%= render 'form' %>

<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/show.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %> <a href="#" data-dismiss="alert" class="close">×</a></p>
<% end %>

  <div class="col-md-3">
    <div class="card card-stats">
    <div class="card-header card-header-success card-header-icon">
    <div class="card-icon">
    <i class="material-icons">store</i>
  </div>
   <p class="card-category"> Account balance:</p>
   <% @bank_total = 0 %>
    <h3 class="card-title"> <% @transactions.each do |transaction| %>
                            <% if transaction.bank_account_id == @bank_account.id %>
                            <% @bank_total += transaction.total_amount.to_f %>
                             <% end %> 
                              <% end %> 
                              <%= @bank_total %></h3>
                            
                         
                            
    </div>
     </div>
     </div>
     </div>
     

<%= link_to 'Add General Payment', new_payment_entry_path, class:'btn btn-warning' %> | <%= link_to 'Add Invoice Payments', payment_entries_invoice_entry_path, class:'btn btn-warning' %> | <%= link_to 'New General Receipts', new_receipt_entry_path, class:'btn btn-success' %> | <%= link_to 'New Invoice Receipts', receipt_entries_invoice_entry_path, class:'btn btn-success' %>

 <div class="card">
     
 <div class="card-body table-responsive">
   <table class="table table-hover">
    <thead class="text-warning">
      <tr>
        <th colspan="0.3"></th>
        <th scope="col">Date</th>
        <th scope="col">Description</th>
        <th scope="col">Account</th>
        <th scope="col">Amount</th>

        <th colspan="1"></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <% @transactions.each do |transaction| %>
         <% if transaction.bank_account_id == @bank_account.id %>
              <td><% if transaction.total_amount < 0 %>
     <h2><strong><center><font color =" #EC971F">•</font></strong></center></h2>
     <% else %>
      <h2><strong><center><font color =" #47A44B">•</font></strong></center></h2>
      <% end %>
      
          <td><div class ="table-color"><%= transaction.date %></div></td>
          <td><div class ="table-color"><%=  transaction.description %></div></td>
         <td> <% if  transaction.gl_account != nil %>
                <div class ="table-color"><%= transaction.gl_account.name %>
          <% else %>

               <%= transaction.contact_id ? transaction.contact_id.name.to_s : "" %></div></td>
      
                <% end %>
          <td><div class ="table-color"><%= link_to transaction.total_amount ? transaction.total_amount.round(2) : ""  %></td>
           <td><%= link_to 'Edit', edit_transaction_path(transaction) %> | 
               <%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
        <%end%>
        <%end%>
      </tbody>
    </table>
    </div>
    </div>

</div>
</div>
<br>

<%= link_to 'Edit', edit_bank_account_path(@bank_account) %> |
<%= link_to 'Back', bank_accounts_path %>

<div class ="pagination

app/views/bank_accounts/unallocated.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %> <a href="#" data-dismiss="alert" class="close">×</a></p>
<% end %>

  <div class="col-md-3">
    <div class="card card-stats">
    <div class="card-header card-header-success card-header-icon">
    <div class="card-icon">
    <i class="material-icons">store</i>
  </div>

                            
                         
                            
    </div>
     </div>
     </div>
     </div>
     

<%= link_to 'Add General Payment', new_payment_entry_path, class:'btn btn-warning' %> | <%= link_to 'Add Invoice Payments', payment_entries_invoice_entry_path, class:'btn btn-warning' %> | <%= link_to 'New General Receipts', new_receipt_entry_path, class:'btn btn-success' %> | <%= link_to 'New Invoice Receipts', receipt_entries_invoice_entry_path, class:'btn btn-success' %>
<%= form_tag import_transactions_path, multipart: true do %>
<div class='btn btn-white col-md-2 btn-small pull-left'><%= file_field_tag :file %></div>
<%= submit_tag 'Import CSV', class: ' col-med-3 btn btn-info'%>
<%end%>



 <div class="card">
     <div class="accordion">
 <div class="card-body table-responsive">
     <table class="table table-hover fold-table">
    <thead class="text-warning">
      <tr>
        <th scope="col">Date</th>
         <th colspan="0.3">Reference</th>
        <th scope="col">Description</th>
        <th scope="col">Account</th>
        <th scope="col">Amount</th>

        <th colspan="1"></th>
      </tr>
      </thead>
      <tbody>

       <% @transactions.each do |transaction| %>
       <% if  transaction.bank_account_id == nil || transaction.gl_account_id == nil %>
          <tr class="view">
          <% if  transaction.amount < 0  %>
             
    <td> <font color =" #EC971F"><%= transaction.date %></font></td>
     <% else %>
    <td>   <font color =" #47A44B"><%= transaction.date %></font></td>
      <% end %>
         <td><div class ="table-color"><%=  transaction.reference %></div></td>
          <td><div class ="table-color"><%=  transaction.description %></div></td>
         <% if transaction.gl_account.present? %>
             <td><div class ="table-color"> <%= transaction.gl_account ? transaction.gl_account.name.to_s : "Not mapped - find this transaction a home!" %></div></td>
              <%else%>
               <td class ='text-danger'><%= transaction.contact_id ? transaction.contact_id.name.to_s : "Not mapped - find this transaction a home!"%></div></td>
               <%end%>
               <td><div class ="table-color"><%= link_to transaction.vat_amount ? transaction.vat_amount.round(3) : ""  %></td>
          <td><div class ="table-color"><%= link_to transaction.amount ? transaction.amount.round(3) : ""  %></td>
           <td><%= link_to 'More', edit_transaction_path(transaction) %> | 
               <%= link_to 'Delete', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </div>
     <tr class="fold">
      <div class="fold-content">
       <%= simple_form_for(transaction, remote: true)  do |f| %>
        <td> <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td>
        <td><%= f.text_field :reference, label: false, class: 'form-control input', placeholder: 'reference'  %></td>
       <td><%= f.text_field :description, label: false, class: 'form-control input', placeholder: 'description'  %></td>
        <td><%= f.collection_select :gl_account_id, GlAccount.all, :id, :name, {:prompt => false},class:"btn btn-sm", id:"office_address"%></td>
         <td><%= f.collection_select :vat_type, Transaction.vat_types.map{ |dp| [dp.first, dp.first.humanize] }, :first, :second,{:prompt => false},class:"btn btn-sm"  %></td>
        <td> <%= f.text_field :amount, class: 'form-control input'  %></td>
         <td><%= f.collection_select :bank_account_id, BankAccount.all, :id, :name, {:prompt => false},class:"btn btn-sm", id:"office_address"%></td>
         <td>   <%= f.submit 'Update Transaction', class: 'btn btn-success btn-sm'%></td> 
       </div>
     </tr>
     
       <%end%>
       <%end%>
         <%end%>
               
       
      </tbody>
    </table>
    </div>
    </div>

</div>
</div>
<br>

<%= link_to 'Edit', edit_transaction_path(@transactions) %> |
<%= link_to 'Back', bank_accounts_path %>

<div class ="pagination