config/routes.rb
Rails.application.routes.draw do

  get 'bank_accounts/unallocated'
  get 'purchases/paid'
  get 'purchases/draft_index'
  get 'purchases/unpaid'
  get 'purchases/partially_paid'
  get 'report/income_statement'
  get 'report/balance_sheet'
  get 'report/trial_balance'
  get 'report/general_ledger'
  get 'payment_entries/invoice_entry'
  get 'receipt_entries/invoice_entry'
   get 'sales/paid'
  get 'sales/draft_index'
  get 'sales/unpaid'
  get 'sales/partially_paid'
  resources :journals
  resources :journal_entries
  resources :products
    get 'purchases/draft'
   get 'purchases/invoice'
  resources :purchase_entries
  resources :purchases
  resources :contacts
  get 'sales/quote'
  get 'sales/draft'
   get 'sales/invoice'
  resources :sales_entries
  resources :sales
  resources :receipt_entries
  resources :payment_entries
  resources :bank_accounts
  resources :gl_accounts
  resources :transactions
  get 'index/home'
 
  root 'index#home'
  
    resources :transactions do 
    collection { post :import }
  end
  resources :bank_accounts do 
    collection { post :import }
  end
  
   resources :transactions do
    collection do
      delete 'destroy_multiple'
    end
  end
 
end

app/models/sale.rb
class Sale < ActiveRecord::Base
      before_save :journal_params, :journal_params
  
    has_many :transactions
    has_many :sales_entries
    belongs_to :contact
    belongs_to :gl_account
    belongs_to :bank_account
    has_many :products
    
       accepts_nested_attributes_for :sales_entries,
                                  allow_destroy: true
    
    
    
    enum sales_type: {
    invoice:       0,
    draft:         1,
    estimate:      2,
 
  }
  
 def set_balance
    
   self.balance = 0.00
    
 end
  
  def update_balance
  update(balance: transactions.sum(:total_amount))
end
  
 def journal_params
  # Use find_all instead of where since you might be dealing with unpersisted records
  self.amount  = sales_entries
                  .find_all(&:price?)
                  .sum { |journal_entry| journal_entry.total_price }
 
  
  end
 
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    @sale_entry = SalesEntry.all
  end
  
    def draft_index
    @sales = Sale.all.where("sales_type =?", 1)
    @sale_entry = SalesEntry.all
  
  end
  
    def partially_paid
    @sales = Sale.all
    @sale_entry = SalesEntry.all
      @transactions = Transaction.all
  end
  
    def paid
    @sales = Sale.all
    @sale_entry = SalesEntry.all
     @transactions = Transaction.all
  end
  
      def unpaid
    @sales = Sale.all
    @sale_entry = SalesEntry.all
     @transactions = Transaction.all
  end
  
  
  

  # GET /sales/1
  # GET /sales/1.json
  def show
   @sale_entry = SalesEntry.all
   @transactions = Transaction.all
  end

  # GET /sales/new
  def new
    @sale = Sale.new
      2.times do
    @sale.sales_entries.build
  end
   @sale.balance = 0
  end
  
   def invoice
    @sale = Sale.new
     2.times do
    @sale.sales_entries.build
end
 @sale.balance = 0
end

  
  def quote
    @sale = Sale.new
     2.times do
    @sale.sales_entries.build
end
 @sale.balance = 0
end
  
    def draft
    @sale = Sale.new
    2.times do
    @sale.sales_entries.build
  end
   @sale.balance = 0
  end

  # GET /sales/1/edit
  def edit

  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.balance = 0
    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:id, :number, :title, :address, :date, :due_date, :vat_total, :balance, :amount, :notes, :customer_id, :account_type, :sales_type, :contact_id, :user_id, sales_entries_attributes: [ :id, :sale_id, :invoice_number, :product_id, :description, :vat_amount, :quantity, :price, :vat_type, :account_id, :total_price, :gl_account_id ])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<div class ="form-fields">
<%= simple_form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center>
<div class= "card col-md-12">
  <div class="card-header card-header-info">
                                    <h4 class="card-title">Edit Invoice</h4>
                                    <p class="card-category"></p>
                                     </div> 
   <table class = "table">
    <thead>
      <tr><center>
           <%= f.hidden_field :balance, :value => 0%>
    <th>  <%= f.label :date %><br></th>
   <th> <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td></th>
   
   <th></th>
   <th>  <%= f.label :customer_id %><br></th>
    <th> <%= f.collection_select(:contact_id, Contact.all, :id, :name, {:prompt => false},  class:"btn ml-auto")  %></th>

     <tr><center>
    <th>  <%= f.label :due_date %><br></th>
   <th> <%= f.date_field :due_date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td></th>
   <th></th>
     <th>  <%= f.label :invoice_number %><%=  f.text_field :invoice_number, class: 'form-control' %></th>
    <th> <%= f.label :sales_type%> <%=  f.select :sales_type, Sale.sales_types.keys, {}, class: 'btn btn-default'   %></th>
   </tr></center>
   </tr></center>
   <th></th>
  </div>
 </div>

</div>
  </br></br></br>
  
 
<div class= "card">
  <table class = "table">
    <thead>
    <tr>
      <th class ="col col-lg-1"></th>
             <th class ="colspan-1">Product</th>
      <th class ="colspan-1">Description</th>
      <th class ="colspan-1">Account</th>
      <th class ="colspan-1">Vat</th>
      <th class ="col col-lg-1">Quantity</th>
      <th class ="col col-lg-2">Amount</th>
      <th class ="col col-lg-2">Total</th>
    </tr>
  </thead>
    

      <div class = "card">
 <tbody class ="fields">
    <%= f.fields_for :sales_entries do |builder| %>
    <%= render 'sales_entry', f: builder %>
    <% end %>
    </div>
  </div>
  </tbody>
  
  </table>
  <%= link_to_add_row('Add line', f, :sales_entries, class: 'btn btn-warning') %>
  </br> </br>
   <%= f.text_area :notes, class: 'form-control', placeholder: 'Notes' %> 
  </div>
  <div class="actions">

    </br></br>
     <%= f.submit 'Create Invoice', :class => 'btn btn-success' %> | <%= link_to 'Back', sales_path, class:"btn btn-default" %>

  </div>
<% end %>
 </center>
 

app/views/sales/draft.html.erb
<div class ="form-fields">
<%= simple_form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center>
<div class= "card col-md-12">
  <div class="card-header card-header-danger">
                                    <h4 class="card-title">Draft</h4>
                                    <p class="card-category"></p>
                                     </div> 
                                  
   <table class = "table">
    <thead>
      <tr><center>
    <th>  <%= f.label :date %><br></th>
   <th> <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td></th>
   <th></th>
   <th>  <%= f.label :customer_id %><br></th>
    <th>  <%=f.collection_select(:contact_id, Contact.all, :id, :name, {:prompt => false},  class:"btn ml-auto") %></th>

     <tr><center>
    <th>  <%= f.label :due_date %><br></th>
   <th> <%= f.date_field :due_date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </td></th>
     <th>  <%= f.label :invoice_entry %><%=  f.text_field :invoice_number, class: 'btn btn-default pull-right'  %></th>
    <th>  <%=  f.select :sales_type, Sale.sales_types.keys, {}, class: 'btn btn-default'   %></th>
   </tr></center>
   </tr></center>
   <th></th></th>
    <th> 
               
        </div></th>
   </tr></center>
   <th></th>
  </div>
 </div>

</div>
  </br></br></br>
  
 
<div class= "card">
  <table class = "table">
    <thead>
        <center>
    <tr>
      <th class ="colspan-1"></th>
       <th class ="colspan-1">Product</th>
        <th class ="colspan-1">Description</th>
      <th class ="colspan-1">Account</th>
       <th class ="colspan-1">Vat</th>
      <th class ="colspan-1">Quantity</th>
      <th class ="colspan-1">Amount</th>
      <th class ="colspan-1">Total</th>
    </tr>
  </thead>
    </center>

      <div class = "card">
 <tbody class ="fields">
    <%= f.fields_for :sales_entries do |builder| %>
    <%= render 'sales_entry', f: builder %>
    <% end %>
    </div>
  </div>
  </tbody>
  
  </table>
  <%= link_to_add_row('Add line', f, :sales_entries, class: 'btn btn-warning') %>
  </br> </br>
   <%= f.text_area :notes, class: 'form-control', placeholder: 'Notes' %> 
  </div>
  <div class="actions">

    </br></br>
     <%= f.submit 'Create draft', :class => 'btn btn-danger' %> | <%= link_to 'Back', sales_path, class:"btn btn-default" %>

  </div>
<% end %>
 </center>
 
 
 

app/views/sales/draft_index.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', sales_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', sales_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', sales_unpaid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', sales_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', sales_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', sales_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
  
      <tr>
        <td><%= link_to sale.date, sale_path(sale) %></td>
        <td><%= sale.contact_id ? sale.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{sale.id}" %></td>
           <td><%= sale.amount %></td>
      
      
             <td>    <% if sale.sales_type == 'invoice' %>
            <%= link_to "Invoice", edit_sale_path(sale), class:"btn btn-success" %></td>
           
            <% else if sale.sales_type == 'draft' %>
            <%= link_to "Draft", edit_sale_path(sale), class:"btn btn-danger" %>
  
          
             <% end %>
             <% end %>
      </td>   
        <td><%= link_to "Edit", edit_sale_path(sale) %> | <%= link_to 'Delete', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/sales/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', sales_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', sales_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', sales_unpaid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', sales_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', sales_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', sales_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Customer</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.date, sale_path(sale) %></td>
        <td><%= sale.contact_id ? sale.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{sale.invoice_number}" %></td>
      <td><%= sale.amount ? sale.amount.to_f.round(2) : "0"%></td>
      
      
             <td>    <% if sale.sales_type == 'estimate' %>
            <%= link_to "Quote", edit_sale_path(sale), class:"btn btn-warning" %></td>
           
            <% else if sale.sales_type == 'draft' %>
            <%= link_to "Draft", edit_sale_path(sale), class:"btn btn-danger" %>
            
          <% else if sale.sales_type == 'invoice' %>
         <%= link_to "Invoice", edit_sale_path(sale), class:"btn btn-success" %></td>
            <% end %>
             <% end %>
             <% end %>
      </td>   
        <td><%= link_to "Edit", edit_sale_path(sale) %> | <%= link_to 'Delete', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/sales/invoice.html.erb
<div class ="form-fields">
<%= simple_form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center>
    </br>
<div class= "card col-md-12">
  <div class="card-header card-header-info">
                                    <h4 class="card-title">Sales Invoice</h4>
                                    <p class="card-category"></p>
                                     </div> 
                                  
   <table class = "table">
    <thead>
      <tr>
    <th>  <%= f.label :date %></th>
   <th> <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </th>
    <th>  <%= f.label :due_date %></th>
    <th> <%= f.date_field :due_date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> </th>
           <th>  <%= f.label :customer_id %></th>
    <th>  <%=f.collection_select(:contact_id, Contact.all, :id, :name, {:prompt => false},  class:"btn ml-auto") %></th>
    </tr>
    <tr>
     <th>  <%= f.label :invoice_number %></th>
     <th><%=  f.text_field :invoice_number, class: 'form-control', placeholder: 'Inv: ***'  %></th>
          <th>  <%= f.label :sales_type %></th>
    <th>  <%=  f.select :sales_type, Sale.sales_types.keys, {}, class: 'btn btn-default'   %></th>
   </tr></center>
  </div>
 </div>
 </thead>
 </table>
  </div>
  </br></br>
 
 
<div class= "card">
  <table class = "table">
    <thead>
    <tr>
      <th class ="colspan-1"></th>
       <th class ="colspan-1">Product</th>
        <th class ="colspan-1">Description</th>
      <th class ="colspan-1">Account</th>
      <th class ="colspan-1">Vat</th>
      <th class ="colspan-1">Quantity</th>
      <th class ="colspan-1">Amount</th>
      <th class ="colspan-1", id ="tot">{total}</th>
    </tr>
  </thead>
    

      <div class = "card">
 <tbody class ="fields">
    <%= f.fields_for :sales_entries do |builder| %>
    <%= render 'sales_entry', f: builder %>
    <% end %>
    </div>
  </div>
  </tbody>
  
  </table>
  <%= link_to_add_row('Add line', f, :sales_entries, class: 'btn btn-info') %>
  </br></br>
   <%= f.text_area :notes, class: 'form-control', placeholder: 'Notes' %> 
  </div>
  <div class="actions">

    </br></br>
     <%= f.submit 'Create Invoice', :class => 'btn btn-info' %> | <%= link_to 'Back', sales_path, class:"btn btn-default" %>

  </div>
<% end %>
 </center>
 
 
 

app/views/sales/paid.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', sales_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', sales_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', sales_unpaid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', sales_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', sales_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', sales_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th> Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <tbody>
    <% @sales.each do |sale| %>
    <% if sale.balance != nil  && sale.balance.to_f >= sale.amount.to_f %>
      <tr>
        <td><%= link_to sale.date,  sale_path(sale)%></td>
        <td><%= sale.contact_id ? sale.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{sale.id}" %></td>
           <td><%= sale.amount %></td>
              <td> <%= sale.balance %> </td>
              <td> <%= sale.amount.to_f - sale.balance.to_f %> </td>
        
             <% end %>
              <% end %>
      </td>   
      
      </tr>

  </tbody>
</table>
</div>

<br>

app/views/sales/partially_paid.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', sales_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', sales_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', sales_unpaid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', sales_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', sales_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', sales_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th> Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <tbody>
    <% @sales.each do |sale| %>
    <% if sale.balance != nil  && sale.balance.to_f < sale.amount.to_f %>
      <tr>
        <td><%= link_to sale.date,  sale_path(sale)%></td>
        <td><%= sale.contact_id ? sale.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{sale.id}" %></td>
           <td><%= sale.amount %></td>
              <td> <%= sale.balance %> </td>
              <td> <%= sale.amount.to_f - sale.balance.to_f %> </td>
        
             <% end %>
              <% end %>
      </td>   
      
      </tr>

  </tbody>
</table>
</div>

<br>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<center>

<div class= "card col-md-10" style="background-color:#fff;">
 
  <% if @sale.sales_type == "invoice" %>
                <div class="card-header card-header-success">
                    <h4 class="card-title">sale</h4>
                      <p class="card-category"></p>
                      </div> 
                              <% else if @sale.sales_type == "draft" %>
                               <div class="card-header card-header-danger">
                                 <h4 class="card-title">Draft</h4>
                                   <p class="card-category"></p>
                                           </div> 
                                           <% else if @sale.sales_type == "Quote" %>
                                             <div class="card-header card-header-warning">
                                               <h4 class="card-title">Draft</h4>
                                                 <p class="card-category"></p>
                                           </div> 
                                     <% end %>
                                     <% end %>
                                     <% end %>
   <table class = "table table-striped">
    <thead >
      <tr><center>
    <th><strong>Date:</strong> </th>
   <th>  <%= @sale.date %> </td></th>
      <th><strong>Total:</strong> </th>
   <th>  <%= @sale.amount.round(2) %> </td></th>
   <th> <strong>Invoice Type:</strong><br></th>
    <th>  <%= @sale.sales_type %></th>
     <th> <strong>Customer:</strong><br></th>
    <th><%= @sale.contact_id ? @sale.contact.name : '' %> </br>
       <%= @sale.contact_id ? @sale.contact.address_one : '' %> </br>
      <%= @sale.contact_id ? @sale.contact.city : '' %> </br>
   </tr></center>
  </div>
 </div>

</div>
  </br></br></br>
  
<div class= "card">

  <table class = "table table-striped">
    <thead style="background-color:#fff;">
    <tr>
      <th>Description</th>
       <th>Product</th>
      <th>Account</th>
      <th>Vat</th>
      <th>Quantity</th>
      <th>Amount</th>
      <th>Total</th>


  </thead>
        <h3><left>Invoice Items</left></h3>
      <tbody style="background-color:#fff;">
       <% @sale_entry.each do |entry| %>
            <% if entry.sale_id == @sale.id %>

               <td>  <%= entry.description %></td>
               <td> <%= entry.product ? entry.product.name : ' ' %></td>
               <td> <%= entry.gl_account ? entry.gl_account.name : ' ' %></td>
                  <td> <%= entry.vat_amount.to_f.round(2) %></td>
               <td> <%= entry.quantity %></td>
               <td> <%= entry.price.to_f.round(2) %></td>
                  <% if entry.quantity.to_i > 0 %>
                     <% @total = 0 %>
                     <% @total += (entry.quantity.to_f.round(2)) * (entry.price.to_f.round(2) + entry.vat_amount.to_f.round(2)) %>
                     <td><strong><%= @total.round(2) %></strong></td>
                     </tr>
                 <% else %>
                     <td><strong><%= entry.price %></strong></td>
              </tr>
                <% end %>
        <% end %>
       <% end %>
   </table>
   
   <h3 class='pull-left'>Payments</h3>
   
   <table class="table table-striped">
                  <thead style="background-color:#fff;">
                  <th class ='col-md-4'><strong>Date</strong></th>
                  <th class ='col-md-4'><strong>Description</strong></th>
                  <th class ='col-md-4'><strong>Reference</strong></th>
                  <th class ='col-md-4'><strong>Amount</strong></th>
              
     <tbody>
                  <% @transactions.each do |transaction| %>
                  <% if transaction.sale_id == @sale.id %>
              
                  <td class ='col-md-4'><%= link_to transaction.date, edit_transaction_path(transaction) %></td>
                   <td class ='col-md-4'><%= transaction.description %></td>
                  <td class ='col-md-4'><%=transaction.reference %></td>
                  <td class ='col-md-4'><%= transaction.total_amount %></td>
                  </tr>
                  
             <% end %>
             <% end %>
              
      </tbody>
      </table>
      
      
      <br><br><br><br> <br><br><br><br>
      <table class ="table table-striped">
      <tbody style="background-color:#fff;">
        <tr style="background-color: #fff;">
       <td class ='col-md-3'><strong><h3>Balance:</h3></strong></td>
        <td class ='col-md-3'></td>
        <td class ='col-md-3'></td>
         <td class ='col-md-3'></td>

        
             <td class ='col-md-3'><strong><h3><% @total_balance = 0 %>
                         <% @total_balance = @sale.amount - @sale.transactions.sum(:total_amount) %> 
                         <%= @total_balance.round(2)  %></h3></strong></td>
       
            </tr>
          </tbody>
          
  </table>
  </div>
  <%= link_to 'Edit', edit_sale_path(@sale), class: "btn btn-default" %> |
<%= link_to 'Back', sales_path ,class:"btn btn-default"%>
 </center>

 
 

app/views/sales/unpaid.html.erb
<% if notice %>
    <p class= 'alert alert-success'><%= notice %></p>
<% end %>
</br>
<%= link_to 'New Invoice', sales_invoice_path,  class: "btn btn-primary col-md-4" %> <%= link_to 'Drafts', sales_draft_index_path,  class: "btn btn-default pull-right" %><%= link_to 'Outstanding', sales_unpaid_path,  class: "btn btn-danger pull-right" %><%= link_to 'Partially Paid', sales_partially_paid_path,  class: "btn btn-warning pull-right" %><%= link_to 'Paid', sales_paid_path,  class: "btn btn-success pull-right" %><%= link_to 'All', sales_path,  class: "btn btn-info pull-right" %>  


<br><br>
<div class= "card">
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th> Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <tbody>
    <% @sales.each do |sale| %>
    <% if sale.balance == nil %>
      <tr>
        <td><%= link_to sale.date,  sale_path(sale)%></td>
        <td><%= sale.contact_id ? sale.contact.name : 'No customer'  %></td>
        <td><%= "Inv #{sale.id}" %></td>
           <td><%= sale.amount.to_f.round(2) %></td>
              <td> <%= sale.balance.to_f.round(2) %> </td>
              <td> <%= sale.amount.to_f.round(2) - sale.balance.to_f.round(2) %> </td>
        
             <% end %>
              <% end %>
      </td>   
      
      </tr>

  </tbody>
</table>
</div>

<br>